general:
  seed: 0
  device: "cuda"

wandb:
  enable: True
  project_name: "csNet"
  entity: "ese5460"
  name: null
  config: null

training:
  dataset:
    shuffle: True
    apply_transformation: True
    # the pecentatages of dataset being used
    dataset_size: 1
    batch_size: 16
  epochs: 50
  optimizor:
    lr: 0.01
    momentum: 0.9
    weight_decay: 1.e-5
    nesterov: True
    lr_decay: 0.95
    
    # the learning rate will not decay after this times of epochs
    end_epoch: 50

testing:
  dataset:
    shuffle: True
    apply_transformation: False
    # the pecentatages of dataset being used
    dataset_size: 1
    batch_size: 16
  ensemble:
    # ensemble method to try
    # ensemble method including: "average", "Kalman filter", "weighted sum", "majority voting"
    methods: ["average", "majority voting", "Kalman filter", "weighted sum"]
    number_of_models: 16
    # for Kalman filter and weighted sum how many runs need for a single model to obtain uncertainty
    num_of_different_result: 16  

networks:
  # number of individual networks
  number_of_models: 16

  transforms:
    # fixed transforms generate policy: 
    # CIFR10:use same CIFR10 autoaugmentation as torch implementation
    # Random:use my random generation policy
    policy: CIFR10

    include_identity: True

  # size of hidden layer
  c1: 96
  c2: 192

  # dropout ratio
  d1: 0.2
  d2: 0.5

paths:
  #pre-trained_model
  model_path: "../pretrained_model/Hien_pretrained_models/experiment_09-Dec-2022_16_23_49/checkpoints/model_epoch50.pth"

  #pre-optimizor info
  optimizer_path: null

  #pre-determined fixed transforms path
  transforms_path: "../pretrained_model/tranforms.json"

  #directory to save the model
  save_directory: "../pretrained_model"


